"""Photo framing pipeline package."""

from .core import (
    AppConfig,
    BorderSpec,
    ProcessRecord,
    RunStats,
    bytes_to_kb,
    fit_inside,
    is_landscape,
    list_source_images,
    load_image,
    process_all,
    render_framed_full,
    render_framed_split_half,
    run_basic_tests,
    size_diagnostics_lines,
    split_landscape_exact,
    summarize_source_images,
    validate_outputs,
)

__all__ = [
    "AppConfig",
    "BorderSpec",
    "ProcessRecord",
    "RunStats",
    "bytes_to_kb",
    "fit_inside",
    "is_landscape",
    "list_source_images",
    "load_image",
    "process_all",
    "render_framed_full",
    "render_framed_split_half",
    "run_basic_tests",
    "size_diagnostics_lines",
    "split_landscape_exact",
    "summarize_source_images",
    "validate_outputs",
]
